call pathogen#infect()

"-- Colors & Fonts --
colorscheme zenburn
if has("win32") || has("win16")
	set guifont=Droid_Sans_Mono:h9
else
	set guifont=Droid\ Sans\ Mono\ 9
endif

"-- Autocomplete --
if !(has("win32") || has("win16")) || has("gui_running")  "Works on non-Windows OS's, and in GVim on Windows... but not in a Cygwin terminal for some reason.
	filetype plugin on
	set completeopt-=preview
endif




"Generated by vimrcgenerator.appspot.com

"-- General --
set number      "Show line numbers
set ruler       "Show the line and column number of the cursor position
set nobackup	"Disable '~' backup files (enabled by default on Windows)

"-- Programming --
set autoindent      "Copy indent from current line when starting a new line
set smartindent     "Do smart indenting when starting a new line. Works with supported c-like languages
syntax on			"Enable syntax highlighting for supported file formats

"-- Spaces/Tabs --
set noexpandtab     "Strictly use tabs when tab is pressed (this is the default)
set shiftwidth=4
set tabstop=4

"-- Searching --
set hlsearch        "Highlight search results
set ignorecase      "When doing a search, ignore the case of letters
set smartcase       "Override the ignorecase option if the search pattern contains upper case letters
"Clear the search highlight by pressing ENTER when in Normal mode (Typing commands)
:nnoremap <CR> :nohlsearch<CR>/<BS><CR>

"-- Tabbed Editing --
"Open a new (empty) tab by pressing CTRL-T. Prompts for name of file to edit
map <C-T> :tabnew<CR>:edit 
"Open a file in a new tab by pressing CTRL-O. Prompts for name of file to edit
map <C-O> :tabfind 
"Switch between tabs by pressing Shift-Tab
map <S-Tab> gt

"-- Tweaks --
"Add tweak for better backspace support
set backspace=indent,eol,start

